apiVersion: v1
kind: PersistentVolume
metadata:
  name: ko-pv #name of pv
spec:
  capacity:
    storage: 2Gi #required
  accessModes:
    - ReadWriteOnce   #
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /exto/ko-space
    type: DirectoryOrCreate