apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ko-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual   #Storage class what pv have
  resources:
    requests:
      storage: 2Gi