apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ko-deploy1
  name: koweb-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ko-deploy1
  type: ClusterIP
status:
  loadBalancer: {}
