apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ko-deploy1
  name: ko-web-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ko-deploy1
  type: LoadBalancer
status:
  loadBalancer: {}
