FROM nginx
#we are asking docker server to pull this image from Docker hub
LABEL name="kovardhanan"
LABEL email="kovardhanan.s@gaeaglobal.com"
#Time to copy my code to image
COPY project-html-website  /usr/share/nginx/html/
#nginx is having default location as /usr/share/nginx/html/
