apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ko-node
  name: ko-node-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ko-node
  type: LoadBalancer
status:
  loadBalancer: {}
